# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  libraryapipostgresql:
    image: libraryapipostgresql
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5177:5177
